FoodDeliveryApplication/Models/Cart.cs
namespace FoodDeliveryApplication.Models
{
    public class Cart
    {
        public string UserName { get; set; }

        public string FoodItem { get; set; }

        public int Quantity { get; set; }

        public string FoodImage { get; set; }

        public int Price { get; set; }

        public int FoodId { get; set; }

        public int RestaurantId { get; set; }

        public int ItemNo { get; set; }

        //public string RestaurantName { get; set; }

        public Cart()
        {

        }

        public Cart(string userName, string foodItem, int quantity, string foodImage, int price, int foodId, int restaurantId, int itemNo)
        {
            this.UserName = userName;
            this.FoodItem = foodItem;
            this.Quantity = quantity;
            this.FoodImage = foodImage;
            this.Price = price;
            this.FoodId = foodId;
            this.RestaurantId = restaurantId;
            ItemNo = itemNo;
            //this.RestaurantName = restaurantName;
        }
    }
}

FoodDeliveryApplication/Models/CustomerDetails.cs
using System.ComponentModel.DataAnnotations;

namespace FoodDeliveryApplication.Models
{
    public class CustomerDetails
    {
        [Required(ErrorMessage = "Address is Required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Phone No is Required")]
        public string PhoneNo { get; set; }

       /* public CustomerDetails(string address, string phoneNo)
        {
            Address = address;
            PhoneNo = phoneNo;
        }*/
    }
}

FoodDeliveryApplication/Models/Menu.cs
namespace FoodDeliveryApplication.Models
{
    public class Menu
    {
        public int Id { get; set; }
        public string food_img { get; set; }

        public string food_item { get; set; }

        public int price { get; set; }

        public int RestaurantId { get; set; }

       
        public Menu()
        {

        }

        public Menu(int Id,string food_img, string food_item, int price, int restaurantId)
        {
            this.Id = this.Id;
            this.food_img = food_img;
            this.food_item = food_item;
            this.price = price;
            this.RestaurantId = restaurantId;
        }

        /* public Menu(string food_img)
         {
             //this.Id = this.Id;
             this.food_img = food_img;
             //this.food_item = food_item;
             //this.price = price;
         }*/
    }
}

FoodDeliveryApplication/Models/Restaurants.cs
namespace FoodDeliveryApplication.Models
{
    public class Restaurants
    {
        public int RestaurantId { get; set; }

        public string RestaurantName { get; set; }

        public string RestaurantImage { get; set; }

        public Restaurants()
        {

        }


        public Restaurants(int restaurantId, string restaurantName, string restaurantImage)
        {
            RestaurantId = restaurantId;
            RestaurantName = restaurantName;
            RestaurantImage = restaurantImage;
        }
    }
}

FoodDeliveryApplication/Controllers/FoodSiteController.cs
using FoodDeliveryApplication.Models;
using FoodDeliveryApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Serilog;
using System.Data.SqlClient;


namespace FoodDeliveryApplication.Controllers
{
    //[CustomExceptionFilter]
    public class FoodSiteController : Controller
    {

        public List<SignUp> userList = new List<SignUp>();
        public string NotExist = "User Not Exist";
        static string CurrUser;
        public List<FoodItems> FoodItemsSelected =  new List<FoodItems>();
        private readonly ILogger<FoodSiteController> _logger;


        public FoodSiteController(ILogger<FoodSiteController> logger)
        {
            _logger = logger;

            SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433;Initial Catalog = FoodDeliveryApplication;Integrated Security=False;User ID=admin;Password=surya1997;");
            SqlCommand cmd = new SqlCommand("select * from Users", conn);
            conn.Open();
            SqlDataReader sr = cmd.ExecuteReader();
            while (sr.Read())
            {
                SignUp user = new SignUp(sr["UserName"].ToString(), sr["Email"].ToString(), sr["Password"].ToString());
                userList.Add(user);
            }
        }
        public IActionResult Index()
        {
    
            return View();
        }


        public IActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAccount(SignUp signup)
        {
                var user = userList.Find(e => e.UserName == signup.UserName);
                if (user != null)
                {
                    ViewBag.UserName = "UserName already Exist";
                        _logger.LogInformation("User:{0} already Exist, unable to create new Account", signup.UserName);
                    return View();
                }

                SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433 ; Initial Catalog = FoodDeliveryApplication ; Integrated Security=False; User ID=admin; Password=surya1997;");
                SqlCommand cmd = new SqlCommand(String.Format("insert into Users values('{0}','{1}','{2}')", signup.UserName, signup.Email, signup.Password), conn);
                conn.Open();
                cmd.ExecuteNonQuery();
                conn.Close();
                Log.Information(String.Format("A new Account Created with UserName {0}", signup.UserName));



            


            _logger.LogInformation(String.Format("A new Account Created with UserName {0}", signup.UserName));
            

            return View("AccountCreated");

        }

        public IActionResult Login()
        {
                        _logger.LogInformation("Login Triggered");
            return View();
        }
        
        
        [HttpPost]
        public IActionResult Login(LoginDetails login)
        {
           
                var user = userList.Find(e => e.UserName == login.UserName);
                if (user == null)
                {
                    ViewBag.NotExist = NotExist;
                           _logger.LogInformation("User does not Exist");
                return View();
                }
                foreach (var i in userList)
                {
                    if (i.UserName == login.UserName && i.Password == login.Password)
                    {
                    //Log.Information(String.Format("{0} Logged in", login.UserName));
                    _logger.LogInformation(String.Format("{0} Logged in", login.UserName));
                    CurrUser = i.UserName;
                    HttpContext.Session.SetString("UserName", login.UserName);
                        return RedirectToAction("Restaurants");
                    }
                }

                ViewBag.IncorrectPassword = "Incorrect Password";
                 _logger.LogError("Invalid User Details Entered");

            return View();

        }

        public IActionResult Logout()
        {

            //Log.Information(String.Format("{0} Logged out", HttpContext.Session.GetString("UserName")));
            _logger.LogInformation("{0} Logged Out", HttpContext.Session.GetString("UserName"));
            return RedirectToAction("Login");
        }

     

        public IActionResult Menu()
        {
            
            return View();
        }

       
        public IActionResult Restaurants()
        {
            if (HttpContext.Session.GetString("UserName") == null)
            {
                _logger.LogInformation("{0} Logged Out", CurrUser);
                return RedirectToAction("Login");
            }
            SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433 ; Initial Catalog = FoodDeliveryApplication ; Integrated Security=False; User ID=admin; Password=surya1997; ");
            SqlCommand cmd = new SqlCommand("select * from Restaurants", conn);
            conn.Open();
            SqlDataReader sr = cmd.ExecuteReader();
            List<Restaurants> res = new List<Restaurants>();
            while(sr.Read())
            {
               Restaurants restaurant = new Restaurants((int)sr["Restaurant_Id"], sr["Restaurant_Name"].ToString(), sr["Restaurant_Image"].ToString());
                res.Add(restaurant);
            }
           
            return View("Restaurants",res);
        }




        public async Task<IActionResult> RestaurantMenu(int Id)
        {
            if (HttpContext.Session.GetString("UserName") == null)
            {
                _logger.LogInformation("{0} Logged Out", CurrUser);
                return RedirectToAction("Login");
            }
            Console.WriteLine("ResId" + Id);



            SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433 ; Initial Catalog = FoodDeliveryApplication ; Integrated Security=False; User ID=admin; Password=surya1997;");
            SqlCommand cmd = new SqlCommand(String.Format("select *  from Food where Restaurant_Id={0}", Id), conn);
            conn.Open();
            SqlDataReader sr = cmd.ExecuteReader();


            //string str;
            HttpContext.Session.SetInt32("ResId", Id);

            var model = new List<Menu>();

            while (sr.Read())
            {
                Menu menu = new Menu((int)sr["Id"], sr["Food_Image"].ToString(), sr["Food_Item"].ToString(), (int)sr["Price"], (int)sr["Restaurant_Id"]);
                int id = (int)sr["Id"];
                Console.WriteLine(id);
                model.Add(menu);
            }





            return View("Menu", model);
        }



        public IActionResult Order()
        {
            return Content(HttpContext.Session.GetString("UserName"));

        }

        [HttpPost]
        public IActionResult AddToCart(IFormCollection col)
        {

            if (HttpContext.Session.GetString("UserName") == null)
            {
                _logger.LogInformation("{0} Logged Out", CurrUser);
                return RedirectToAction("Login");
            }
            Console.WriteLine(col["Food_Item"]);
            //Console.WriteLine("Food Id :" +col["Food_Id"]);
            var Food_Item = col["Food_Item"];
            var Quantity = col["Quantity"];
            var Restaurant_Id = col["RestaurantId"];
            var Food_Id = Convert.ToInt32(col["Food_Id"]);
            var Price = Convert.ToInt32(col["Price"]);

            _logger.LogInformation("Item:{0} added to cart by the user:{1} of Quantity:{2}", Food_Item, HttpContext.Session.GetString("UserName"), Quantity);


            SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433 ; Initial Catalog = FoodDeliveryApplication ; Integrated Security=False; User ID=admin; Password=surya1997;");
            SqlCommand cmd = new SqlCommand(String.Format("insert into AddItemToCart values('{0}','{1}','{2}','{3}','{4}')", HttpContext.Session.GetString("UserName"), Food_Item, Quantity,Restaurant_Id,Price), conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();

            //Tempdata["success"] = "Item Added to Cart";
            TempData["success"] = "Item Added to Cart";

            return RedirectToAction("RestaurantMenu",new { Id = Restaurant_Id });

          

        }

       
        public IActionResult DeleteItemFromCart(/*IFormCollection col,*/int Id)
        {/*
            string FoodItem = col["FoodItem"];

            int ItemNo = Convert.ToInt32(col["ItemNo"]);*/

          /*  Console.WriteLine("FoodItem = " + FoodItem);*/
           
            SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433 ; Initial Catalog = FoodDeliveryApplication ; Integrated Security=False; User ID=admin; Password=surya1997;");
            SqlCommand cmd = new SqlCommand(String.Format("delete from AddItemToCart where ItemNo = '{0}'", Id), conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();

            TempData["success"] = "Item Removed From Cart";
            return RedirectToAction("Cart");
        }


        public IActionResult Cart()
        {
            if(HttpContext.Session.GetString("UserName")==null)
            {
                _logger.LogInformation("{0} Logged Out", CurrUser);
                return RedirectToAction("Login");
            }
            SqlConnection conn = new SqlConnection("Data Source = fooddeliverydatabase.ctzhubalbjxo.ap-south-1.rds.amazonaws.com,1433 ; Initial Catalog = FoodDeliveryApplication ; Integrated Security=False; User ID=admin; Password=surya1997;");

FoodDeliveryApplication/Views/FoodSite/AccountCreated.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h4>Account Created Successfully!!</h4>
<a asp-controller="FoodSite" asp-action="Login">Login</a>

FoodDeliveryApplication/Views/FoodSite/CancelOrder.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="d-flex justify-content-between">
    <h2 class="text-success">
        Your Order has been cancelled!
    </h2>

    <a asp-controller="FoodSite" asp-action="OrderStatus" class="btn btn-primary" style="font-size:20px">Order Status</a>
</div> 

FoodDeliveryApplication/Views/FoodSite/Cart.cshtml
@using System.Data.SqlClient
@model List<Cart>


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@{
    int Total_Price = 0;
    int Id = 0;
}



@if(ViewBag.Cart=="Empty"){
    <h4 class="text-danger">Your Cart is Empty</h4>
    <a asp-controller="FoodSite" asp-action="Restaurants" class="btn btn-primary">Add Item To Cart</a>
}
else
{

@*@using(@Html.BeginForm("DeleteItemFromCart","FoodSite",FormMethod.Post))
@*<form method="post">*@
//{

    
<table>
    @foreach(var obj in Model)
    {
      

         <tr>
              <th><img src="@obj.FoodImage" style="width:250px; height:250px ; margin-left:30px;margin-right:30px;margin-top:30px" /></th>
              <td>@obj.FoodItem
              <br/>
              Price : @obj.Price
              <br/>
              Quantity : @obj.Quantity
              <br/>
              <br/>
               @* <div class="d-none">
                    <input name="FoodItem" value="@obj.FoodItem"/>
                </div>*@
              <a class="btn btn-primary" asp-controller="FoodSite" asp-action="DeleteItemFromCart" asp-route-Id="@obj.ItemNo">Remove</a>
              </td>
                </tr>
                Total_Price = Total_Price + @obj.Price * obj.Quantity;

                {
                   @* SqlConnection conn = new SqlConnection("Data Source = PSL-28MH6Q3 ; Initial Catalog = FoodDeliveryApplication; Integrated Security = True;");
                    SqlCommand cmd = new SqlCommand(String.Format("insert into ConfirmOrder(UserName,FoodItem,Price,Quantity,RestaurantId) values('{0}','{1}','{2}','{3}','{4}')",@obj.UserName, @obj.FoodItem, @obj.Price,@obj.Quantity,@obj.RestaurantId), conn);
                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();*@
                }
                Id = @obj.RestaurantId;
               
            }

</table>
<br/>
<h4>Total Price : @Total_Price</h4>
<br/>
 Console.WriteLine("RestaurantId:"+Id);
<a class="btn btn-primary" asp-controller="FoodSite" asp-action="CustomerDetails" type="submit" >Add Details</a>
<a class="btn btn-primary" asp-controller="FoodSite" asp-action="Restaurants">Add Items</a>  


    //}
 
}

FoodDeliveryApplication/Views/FoodSite/CreateAccount.cshtml
@model SignUp

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



@*-------------------------------*@

<form method="post">
    <div class="border p-3 mt-4 container  align-self-center " style="width:40%">

        <div class="p-3 mt-4 container align-self-center">
            @if(ViewBag.UserName == "UserName already Exist")
            {
                <p class="text-danger">UserName already exist</p>
            }
            @if(ViewBag.Email == "Email already Exist")
            {
                <p class="text-danger">Email already exist</p>
            }
            <h3>Sign up</h3>
            <br />
            <div class="mb-3">
                @*<label asp-for="UserName"></label>*@
                <input asp-for="UserName" placeholder="User Name" class="form-control" style="width:100%"/>
            </div>

             <div class="mb-3">
                @*<label asp-for="Email"></label>*@
                <input asp-for="Email" placeholder="Email" class="form-control" style="width:100%"/>
            </div>

             <div class="mb-3">
                @*<label asp-for="Password"></label>*@
                <input asp-for="Password" placeholder="Password" class="form-control" style="width:100%"/>
            </div>

            <button type="submit" class="btn btn-outline-primary" style="width:100% ">Create</button>

            <p>Already have an account ?<a asp-controller="FoodSite" asp-action="Login" class="text-danger"> Login</a></p>

        </div>

      
        
    </div>

</form>

FoodDeliveryApplication/Views/FoodSite/CustomerDetails.cshtml
@model CustomerDetails

<form method="post">
    <div class="border p-3 mt-4 container  align-self-center align-items-center" style="width:40%">

        <div style="vertical-align:middle" class="align-items-center">
           
            <h3>Enter Details</h3>
            <br />
            <div class="mb-3">
                <input asp-for="Address" placeholder="Address" class="form-control" style="width:100%"/>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

             <div class="mb-3">
                <input asp-for="PhoneNo" placeholder="Phone number" class="form-control" style="width:100%"/>
            </div>
            
            <button type="submit" class="btn btn-outline-primary" style="width : 100%" asp-controller="FoodSite" asp-action="PlaceOrder">Place Order</button>

           

        </div>

      
        
    </div>

</form>

FoodDeliveryApplication/Views/FoodSite/Login.cshtml
@model LoginDetails

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@*<div style="background-image: url('https://d1tgh8fmlzexmh.cloudfront.net/ccbp-responsive-website/foodmunch-banner-bg.png');background-repeat:no-repeat;background-position:center;width:100vw;height:100vh;margin:auto;">*@

<form method="post">
    <div class="border p-3 mt-4 container  align-self-center align-items-center" style="width:40%">

        <div style="vertical-align:middle" class="align-items-center">
            @if(ViewBag.NotExist == "User Not Exist")
            {
                <p class="text-danger">User Does not Exist</p>
            }
            @if(ViewBag.IncorrectPassword == "Incorrect Password")
            {
                <p class="text-danger">Incorrect Password</p>
            }
            <h3>Log in</h3>
            <br />
            <div class="mb-3">
                @*<label asp-for="UserName"></label>*@
                <input asp-for="UserName" placeholder="User Name" class="form-control" style="width:100%"/>
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

             <div class="mb-3">
                @*<label asp-for="Password"></label>*@
                <input asp-for="Password" placeholder="Password" class="form-control" style="width:100%"/>
            </div>
            
            <button type="submit" class="btn btn-outline-primary" style="width : 100%" >Log in</button>

            <p>New to Zomato? <a asp-controller="FoodSite" asp-action="CreateAccount" class="text-danger">Sign up</a></p>

        </div>

      
        
    </div>

</form>
</div>

FoodDeliveryApplication/Views/FoodSite/Menu.cshtml
@model List<Menu> 

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<script>
    function increaseCount(a, b) {
  var input = b.previousElementSibling;
  var value = parseInt(input.value, 10);
  value = isNaN(value) ? 0 : value;
  value++;
  input.value = value;
}

function decreaseCount(a, b) {
  var input = b.nextElementSibling;
  var value = parseInt(input.value, 10);
  if (value > 1) {
    value = isNaN(value) ? 0 : value;
    value--;
    input.value = value;
  }
}
</script>




<div class="d-flex justify-content-between">
    <h2 class="text-success">
        Menu
    </h2>
  @*  <p style="font-size:20px" class="btn btn-primary text-black ">@Html.ActionLink("Cart","Cart")</p>*@
    <table>
        
        <tr><td><p style="font-size:15px">@Html.ActionLink("Log Out","Logout")</p></td></tr>
        <tr> <td><p style="font-size:15px">@Html.ActionLink("Order History","OrderStatus")</p></td></tr>
        <tr> <td><p style="font-size:15px">@Html.ActionLink("Cart","Cart")</p></td></tr>
        
    </table>
</div> 



<table>
 
        @foreach(var obj in Model)
        {
        @using (@Html.BeginForm("AddToCart","FoodSite",FormMethod.Post))
        {
          @*  <input type="hidden" value="@obj.Id" name="Food_Id"/>*@
         <tr>
                       
                     <th><img src="@obj.food_img" style="width:250px; height:250px ; margin-left:30px;margin-right:30px;margin-top:30px" /></th>
                     <td ><div  readonly>@obj.food_item</div>
                         <div class="d-none">
                             <input name="Food_Item" value="@obj.food_item"/>
                         </div>
                         
                       @*  <div class="d-none">
                             <input name="Food_Id" value="@obj.Id"/>
                         </div>*@

                         <div class="d-none">
                             <input name="RestaurantId" value="@obj.RestaurantId"/>
                         </div>
                        
                         <br/>
                         Price : @obj.price
                         
                         <div class="d-none">
                             <input name="Price" value="@obj.price"/>
                         </div>

                         <br/>
                         <div class="counter">
                              <span class="down" onClick='decreaseCount(event, this)'>-</span>
                              <input type="text" readonly value="1" style="width:50px" class="text-center" name="Quantity">
                              <span class="up" onClick='increaseCount(event, this)'>+</span>
                         </div>
                         <br/>
                         
                         <button class="btn btn-primary" type="submit">Add to Cart</button>
                     </td>
                </tr>


        }
       
          
           
            
        }
        
  
</table>

FoodDeliveryApplication/Views/FoodSite/OrderStatus.cshtml
@model List<OrderDetails>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="d-flex justify-content-between">
    <h2 class="text-success">
        OrderStatus
    </h2>
    <table>
        
        <tr><td><p style="font-size:15px">@Html.ActionLink("Log Out","Logout")</p></td></tr>
        <tr> <td><p style="font-size:15px">@Html.ActionLink("Back","Restaurants")</p></td></tr>

        
    </table>
    </div>

 

<a asp-controller="Foodsite" asp-action="Status" asp-route-id="1" class="btn btn-primary">Pending Orders</a>
@*<a asp-controller="Foodsite" asp-action="Status"  asp-route-id="2" class="btn btn-primary">Cancelled Orders</a>*@
<a asp-controller="Foodsite" asp-action="Status"  asp-route-id="3" class="btn btn-primary">Completed Orders</a>

<br/>
<br/>
<br/>

@if (ViewBag.ObjectPassed == "Pending")
{

        List<OrderDetails> sorted = Model.OrderBy(x => x.OrderTime).ToList();

        int count = Model.Count;
        int tempInvoiceNo = 0;
        @foreach (var obj in sorted)
        {
             
            @if (tempInvoiceNo == @obj.InVoiceNo)
            {
                <h6>Food Item : @obj.FoodItem</h6>
                <p>Quantity : @obj.Quantity</p>
                <p>Price : @obj.Price</p>
            }
            else
            {
                <br/>
                <br/>
                tempInvoiceNo = @obj.InVoiceNo;
                <h4>Order : @obj.InVoiceNo</h4>
                <h5>Order Time : @obj.OrderTime</h5>
                <h6>Food Item : @obj.FoodItem</h6>
                <p>Quantity : @obj.Quantity</p>
                <p>Price : @obj.Price</p>
            }
           
        }
}

@if(ViewBag.ObjectPassed=="Completed")
{

     List<OrderDetails> sorted = Model.OrderBy(x => x.OrderTime).ToList();
         int tempInvoiceNo = 0;
         foreach (var obj in sorted)
        {
            
            if (tempInvoiceNo == @obj.InVoiceNo)
            {
                <h6>Food Item : @obj.FoodItem</h6>
                <p>Quantity : @obj.Quantity</p>
                <p>Price : @obj.Price</p>
            }
            else
            {
                <p>-----------------------------</p>
                tempInvoiceNo = @obj.InVoiceNo;
                <h4>Order : @obj.InVoiceNo</h4>
                <h5>Order Delivered on : @obj.OrderTime</h5>
                <h6>Food Item : @obj.FoodItem</h6>
                <p>Quantity : @obj.Quantity</p>
                <p>Price : @obj.Price</p>
            }
        }

    
}









 @*<table  class="table table-striped">
        <tr>

                <th>Food Item</th>
                <th>Quantity</th>
                <th>Price</th>
        </tr>
        @foreach(var obj in Model)
        {

            <tr>


                <td>@obj.FoodItem</td>

                <td>@obj.Quantity</td>

                <td>@obj.Price</td>


            </tr>
        }
</table>
*@

FoodDeliveryApplication/Views/FoodSite/PlaceOrder.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="d-flex justify-content-between">
    <h3 class="text-success">
        Your Order will be delivered soon! 

    </h3>

    
    <table>
        
        <tr><td><a asp-controller="FoodSite" asp-action="OrderStatus"  style="font-size:20px">Orders</a></td></tr>
        @*<tr> <td><a asp-controller="FoodSite" asp-action="CancelOrder" style="font-size:20px">Cancel Order</a></td></tr>*@
        
        
    </table>
</div> 

FoodDeliveryApplication/Views/FoodSite/Restaurants.cshtml
@model List<Restaurants>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@*<h1>Restaurants</h1>*@



<div class="d-flex justify-content-between">
    <h2 class="text-success">
        Restaurants
    </h2>
    <table>
        
        <tr><td><p style="font-size:15px">@Html.ActionLink("Log Out","Logout")</p></td></tr>
        <tr> <td><p style="font-size:15px">@Html.ActionLink("Order History","OrderStatus")</p></td></tr>
        <tr> <td><p style="font-size:15px">@Html.ActionLink("Cart","Cart")</p></td></tr>
        
    </table>
    </div>
    

     


<div style="display: flex;justify-content: flex-start;align-items: center;">


@foreach(var obj in Model)
{  
    <table>
        <tr>
            <td>
                <a asp-controller="FoodSite" asp-action="RestaurantMenu" asp-route-id="@obj.RestaurantId"><img src="@obj.RestaurantImage" style="width:250px; height:250px; margin-left:30px;margin-right:30px;margin-top:30px"/></a>
   
            </td>
           
        </tr>
        <tr>
             <td>
                 <p style="margin-left:30px">@obj.RestaurantName</p>
            </td>
        </tr>
    </table>
    
   
   

    
} </div>